Fix release workflows to disconnect from pypi
SINTEF/oteapi-dlite-Mod pull request #4
Opened 2024-03-15 09:08 UTC by Treesarj

# Description:

## Type of change:

- [ ] Bug fix.
- [ ] New feature.
- [ ] Documentation update.

## Checklist for the reviewer:

This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand, including clearly named variables?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

2024-03-15 13:42 UTC, Treesarj commented
Maybe we can remove certain steps in the CD_release.yml as it doesn't have access to certain env variables /secrets?

2024-03-18 07:59 UTC, CasperWA requested changes
I thought we were using `SINTEF/ci-cd` here. That workflow has an option to _not_ publish on PyPI using the `publish_on_pypi` input parameter. This one does not.
But here it is as easy as removing that step in the workflow.

Indeed, for this to work in a more optimized way, `SINTEF/ci-cd` callable workflows should be used. In any case - this is fine, as long as the publish to pypi step is removed :)

2024-03-18 07:59 UTC, CasperWA commented on .github/workflows/cd_release.yml
> +        publish_on_pypi: false
Remove this step altogether.

2024-03-18 13:34 UTC, CasperWA approved these changes
This should be fine :)

2024-03-18 13:36 UTC, merged